#pragma once
#include <pebble.h>
#include "commonTypes.h"

extern GFont s_font;

static const int ABILITIES_NAME_RESOURCE_IDS[] =
{
	RESOURCE_ID_BEAM,
	RESOURCE_ID_CUTTER,
	RESOURCE_ID_FIRE,
	RESOURCE_ID_HAMMER,
	RESOURCE_ID_MIKE,
	RESOURCE_ID_SLEEP,
	RESOURCE_ID_SWORD,
};

static const AbilityAnimation BEAM_ANIMATIONS[] =
{
	{RESOURCE_ID_KIRBY_BEAM_ANIM, {24, 52}}
};

static const AbilityAnimation CUTTER_ANIMATIONS[] =
{
	{RESOURCE_ID_KIRBY_CUTTER_THROW_ANIM, {27, 110}},
	{RESOURCE_ID_KIRBY_CUTTER_COMBO_ANIM, {17, 41}}
};

static const AbilityAnimation FIRE_ANIMATIONS[] =
{
	{RESOURCE_ID_KIRBY_FIRE_ANIM, {26, 101}}
};

static const AbilityAnimation HAMMER_ANIMATIONS[] =
{
	{RESOURCE_ID_KIRBY_HAMMER_POUND_ANIM, {12, 99}},
	{RESOURCE_ID_KIRBY_HAMMER_FIRE_ANIM, {0, 73}}
};

static const AbilityAnimation MIKE_ANIMATIONS[] =
{
	{RESOURCE_ID_KIRBY_MIKE_ANIM_1, {19, 109}},
	{RESOURCE_ID_KIRBY_MIKE_ANIM_2, {17, 109}},
	{RESOURCE_ID_KIRBY_MIKE_ANIM_3, {23, 81}}
};

static const AbilityAnimation SLEEP_ANIMATIONS[] =
{
	{RESOURCE_ID_KIRBY_SLEEP_ANIM, {22, 83}}
};

static const AbilityAnimation SWORD_ANIMATIONS[] =
{
	{RESOURCE_ID_KIRBY_SWORD_ANIM, {9, 81}}
};

static const unsigned int NUM_ABILITY_ANIMATIONS[] =
{
	1,  // Beam
	2,  // Cutter
	1,  // Fire
	2,  // Hammer
	3,  // Mike
	1,  // Sleep
	1,  // Sword
};

static const AbilityAnimation* ABILITY_ANIMATION_SETS[] =
{
	BEAM_ANIMATIONS,
	CUTTER_ANIMATIONS,
	FIRE_ANIMATIONS,
	HAMMER_ANIMATIONS,
	MIKE_ANIMATIONS,
	SLEEP_ANIMATIONS,
	SWORD_ANIMATIONS,
};

static const AbilityAnimation INTRO_ANIMATIONS[] =
{
	{RESOURCE_ID_KIRBY_BEAM_INTRO_ANIM, {21, 113}},
	{RESOURCE_ID_KIRBY_CUTTER_INTRO_ANIM, {26, 109}},
	{RESOURCE_ID_KIRBY_FIRE_INTRO_ANIM, {26, 104}},
	{RESOURCE_ID_KIRBY_HAMMER_INTRO_ANIM, {18, 99}},
	{RESOURCE_ID_KIRBY_MIKE_INTRO_ANIM, {30, 119}},
	{RESOURCE_ID_KIRBY_SLEEP_INTRO_ANIM, {20, 111}},
	{RESOURCE_ID_KIRBY_SWORD_INTRO_ANIM, {20, 95}},
};


#define NUM_ABILITIES 7

#define ABILITY_NAME_LAYER_ORIGIN GPoint(14, 25)

#define HUD_KIRBY_LAYER_RECT GRect(0, 0, 96, 41)
#define HUD_BOSS_LAYER_RECT GRect(104, 0, 96, 41)
#define TIME_LAYER_RECT GRect(10, 175, 82, 38)
#define DATE_RECT GRect(109, 175, 82, 38)
#define TEMPERATURE_RECT GRect(108, 175, 82, 38)

#define ZEROTWO_ORIGIN GPoint(50, 35)
#define KING_ORIGIN GPoint(117, 90)
#define KRACKO_ORIGIN GPoint(94, 66)
#define KRACKO_RAIN_ORIGIN GPoint(94, 36)
#define MR_BRIGHT_ORIGIN GPoint(129, 93)
#define MR_SHINE_ORIGIN GPoint(132, 105)
#define MR_FROSTY_ORIGIN GPoint(132, 105)

#define ZEROTWO_NAME_ORIGIN GPoint(113, 23)
#define KING_NAME_ORIGIN GPoint(113, 23)
#define KRACKO_NAME_ORIGIN GPoint(137, 25)
#define MR_BRIGHT_NAME_ORIGIN GPoint(116, 25)
#define MR_SHINE_NAME_ORIGIN GPoint(127, 25)
#define MR_FROSTY_NAME_ORIGIN GPoint(115, 25)

#define INITIAL_ANIMATION_GETTER &(INTRO_ANIMATIONS[abilityIdx])
#define FONT s_font